### PR TITLE
ID: 34neo4ggwc1nrds add dart-hello

### PR DESCRIPTION
**Pull request by LostPengK**
{
  "services": {
    "web": {
      "name": "web",
      "available": 1,
      "total": 1,
      "uris": [
        "11mopgotu9fnhclq14a5kksloo.provider3.akashdev.net"
      ],
      "observed-generation": 0,
      "replicas": 0,
      "updated-replicas": 0,
      "ready-replicas": 0,
      "available-replicas": 0
    }
  },
  "forwarded-ports": {}
}

### CODE REVIEW

**Review by boz — CHANGES_REQUESTED** [review]
Please add to a category such as **Development Tools** in the top-level `README.md`.

**Comment by boz** [comment]
@LostPengK I meant add a link in the [project root `README.md`](https://github.com/ovrclk/awesome-akash/blob/master/README.md), just like all of the other entries.

**Review by boz — CHANGES_REQUESTED** [review]
Please rebase your changes against the current master branch.  It is very out of date.

**Comment by LostPengK** [comment]
sorry, a little chaos ,I'll ceate a new PR.

**Pull request closed without merging**
