### PR TITLE
Add bandano mainnet & readme

### PR DESCRIPTION
**Pull request by voeux-blamer**
Deploy Banano node on Mainnet on Akash.
SDL file + Readme

### CODE REVIEW

**Comment by voeux-blamer** [comment]
Deploy Banano node on Mainnet on Akash.
SDL file + Readme

**Comment by andy108369** [comment]
@voeux-blamer please move the Readme.md to the banano/ directory and update the top-level README.md in the repo.
Thank you.

**Comment by Dimokus88** [comment]
Hey @voeux-blamer !
Can you add the necessary information so that the merge can be completed?

**Comment by Dimokus88** [comment]
This is not answered too, propose close PR @brewsterdrinkwater

**Pull request closed without merging**
