### PR TITLE
Discourse on Akash: Working SDL and deployment guide

### PR DESCRIPTION
**Pull request by jonathanf**
**Project name:** Discourse on Akash
**List of members:** Just me
**A description of your project:** 

This guide and fully functional SDL is intended to describe the process to run Discourse Multi-Tiered application on Akash Network.

The SDL deploy a Multi-Tiered application with 4 services/containers:

### Backend

- PostgreSQL

- Redis

- Sidekiq discourse

### Frontend

- Discourse

**Demo deployment video using Akashlytics:**

 [Discourse on Akash Network](https://youtu.be/XFweRMMZ10s)

### CODE REVIEW

**Comment by jonathanf** [comment]
Also ths PR has fix the Odoo SDL, also tested and 100% functional on mainnet

**Comment by colinlowenberg** [comment]
This pull request has been mentioned on **Akash Community**. There might be relevant details there:

https://forum.akash.network/t/working-multi-tiered-discourse-on-akask-sdl/3096/1

**Comment by dmikey** [comment]
Please rebase there are merge conflicts

**Comment by jonathanf** [comment]
Done.

**Comment by jonathanf** [comment]
Sorry I've use my (testing) self develop plugin for git, I see it have a bug and made a mess here. Tell me if there is not a problem if I reset my fork and resend the PR.

**Comment by jonathanf** [comment]
Done.

**Pull request merged**
