### PR TITLE
feat(nextjs): Add nextjs template and small readme pointing to a full…

### PR DESCRIPTION
**Pull request by 0xFable**
… guide

Adds nextjs a popular framework for enabling React based web applications functionalities such as server-side rendering and generating static websites.

Let me know if this is helpful and I will add more web frameworks

### CODE REVIEW

**Comment by 0xFable** [comment]
Hey @boz , any chance ofreview ? Would like to test this out in Akashyltics app

**Review by boz — CHANGES_REQUESTED** [review]
Thanks @0xFable!  Can you add an entry to the top-level `README.md`?

**Comment by 0xFable** [comment]
Didnt see this originally 
Added a top level item with a new web framework section :D 
@boz

**Comment by 0xFable** [comment]
@boz Can we merged this ser? Responded to review

**Review by boz — APPROVED** [review]
sorry for the delay!

**Pull request merged**
