### PR TITLE
ID 2bc6gmdlyjtq51s: Add Grav to Blogging apps

### PR DESCRIPTION
**Pull request by stakezone**
{
  "services": {
    "grav": {
      "name": "grav",
      "available": 1,
      "total": 1,
      "uris": [
        "r96u9loocd9ob68ic7fodufef4.provider2.akashdev.net"
      ],
      "observed-generation": 0,
      "replicas": 0,
      "updated-replicas": 0,
      "ready-replicas": 0,
      "available-replicas": 0
    }
  },
  "forwarded-ports": {}
}

### CODE REVIEW

**Review by boz — CHANGES_REQUESTED** [review]
Looks great!  Please add an entry to the top-level `README.md`.  Thanks!

**Comment by stakezone** [comment]
update README.md with a link to the Grav project page, that is how I understood the review. I can leave out everything below the link, and just have a basic description linking to Grav.

**Review by boz — CHANGES_REQUESTED** [review]
I meant add a link in the [project root `README.md`](https://github.com/ovrclk/awesome-akash/blob/master/README.md), just like all of the other entries.

**Comment by stakezone** [comment]
the pr should be ok now, root README.md was updated

**Pull request merged**
